#FOR GOOGLE CLOUD APP ENGINE FLEX USE
runtime: python
env: flex
entrypoint: gunicorn ccf.wsgi

beta_settings:
    cloud_sql_instances: <CLOUD_SQL_CONNECTION_STRING>
runtime_config:
  python_version: 3
env_variables:
  SQL_DB_NAME: '<SQL_DB_NAME>'
  SQL_USERNAME: '<SQL_USERNAME>'
  SQL_PASSWORD: '<SQL_PASSWORD>'
  SQL_UNIX_HOSTNAME: '<SQL_UNIX_HOSTNAME>'
  GCS_STATIC_STORAGE: '<GCS_STATIC_STORAGE>'
  DJANGO_SETTINGS_MODULE: 'ccf.settings'
  DJANGO_SECRET_KEY: '<DJANGO_SECRET_KEY>'
  SECURE_COOKIE: 'True'
  USPS_USER_ID: '<USPS_USER_ID>'
  #TWILIO IS OPTIONAL BUT HIGHLY RECOMMENDED
  #TWILIO_SERVICE_SID: '<INSERT SERVICE SID>' 
  #TWILIO_SMS_SENDER: '<INSERT SMS SENDER>'
  #TWILIO_ACCOUNT_SID: '<INSERT SID>'
  #TWILIO_AUTH_TOKEN: '<INSERT AUTH TOKEN>'
